import type { SurveyConfig } from '@/types/survey'

export const maibotFeedbackSurvey: SurveyConfig = {
  id: 'maibot-feedback-v1',
  version: '1.0.0',
  title: '麦麦使用体验反馈问卷',
  description: '感谢您使用麦麦！您的反馈将帮助我们打造更好的 AI 伙伴。',
  questions: [
    {
      id: 'maibot_version',
      type: 'text',
      title: '你正在使用的麦麦版本',
      description: '此项由系统自动填写',
      required: true,
      readOnly: true,
      placeholder: '自动检测中...',
    },
    {
      id: 'improvement_areas',
      type: 'textarea',
      title: '你认为麦麦还有哪些部分可以改进？',
      required: true,
      placeholder: '请分享你认为可以改进的方面...',
      maxLength: 1000,
    },
    {
      id: 'problems_encountered',
      type: 'multiple',
      title: '你在使用麦麦时遇到过哪些问题？',
      description: '可多选',
      required: true,
      options: [
        { id: 'incomplete', label: '功能不完整', value: 'incomplete' },
        { id: 'slow_response', label: '响应速度慢', value: 'slow_response' },
        { id: 'complex', label: '操作复杂', value: 'complex' },
        { id: 'unstable', label: '运行不稳定', value: 'unstable' },
        { id: 'config_difficult', label: '配置困难', value: 'config_difficult' },
        { id: 'none', label: '没有遇到问题', value: 'none' },
        { id: 'other', label: '其他', value: 'other' },
      ],
    },
    {
      id: 'problems_other',
      type: 'text',
      title: '如选择"其他"，请说明遇到的问题',
      required: false,
      placeholder: '请描述你遇到的其他问题...',
      maxLength: 500,
    },
    {
      id: 'helpful_features',
      type: 'textarea',
      title: '你觉得麦麦的哪些功能对你最有帮助？',
      required: true,
      placeholder: '请分享对你最有帮助的功能...',
      maxLength: 1000,
    },
    {
      id: 'feature_requests',
      type: 'textarea',
      title: '你希望在未来的版本中增加哪些功能？',
      required: true,
      placeholder: '请告诉我们你期望的新功能...',
      maxLength: 1000,
    },
    {
      id: 'overall_satisfaction',
      type: 'single',
      title: '你对麦麦的整体满意度如何？',
      required: true,
      options: [
        { id: 'very_satisfied', label: '非常满意', value: 'very_satisfied' },
        { id: 'satisfied', label: '满意', value: 'satisfied' },
        { id: 'neutral', label: '一般', value: 'neutral' },
        { id: 'dissatisfied', label: '不满意', value: 'dissatisfied' },
        { id: 'very_dissatisfied', label: '非常不满意', value: 'very_dissatisfied' },
      ],
    },
    {
      id: 'would_recommend',
      type: 'single',
      title: '你愿意推荐麦麦给其他人使用吗？',
      required: true,
      options: [
        { id: 'yes', label: '是', value: 'yes' },
        { id: 'no', label: '否', value: 'no' },
      ],
    },
    {
      id: 'other_suggestions',
      type: 'textarea',
      title: '其他建议或意见',
      description: '此项为选填',
      required: false,
      placeholder: '如果你有任何其他想法或建议，请在此分享...',
      maxLength: 2000,
    },
  ],
  settings: {
    allowMultiple: false,
    thankYouMessage: '感谢你的反馈！你的意见对麦麦的成长非常重要，我们会认真考虑每一条建议。',
  },
}
