import type { SurveyConfig } from '@/types/survey'

export const webuiFeedbackSurvey: SurveyConfig = {
  id: 'webui-feedback-v1',
  version: '1.0.0',
  title: '麦麦 WebUI 使用反馈问卷',
  description: '感谢您使用麦麦 WebUI！您的反馈将帮助我们不断改进产品体验。',
  questions: [
    {
      id: 'webui_version',
      type: 'text',
      title: '你正在使用的 WebUI 版本',
      description: '此项由系统自动填写',
      required: true,
      readOnly: true,
      placeholder: '自动检测中...',
    },
    {
      id: 'ui_design_satisfaction',
      type: 'single',
      title: '你觉得当前的 WebUI 界面设计如何？',
      required: true,
      options: [
        { id: 'very_satisfied', label: '非常满意', value: 'very_satisfied' },
        { id: 'satisfied', label: '满意', value: 'satisfied' },
        { id: 'neutral', label: '一般', value: 'neutral' },
        { id: 'dissatisfied', label: '不满意', value: 'dissatisfied' },
        { id: 'very_dissatisfied', label: '非常不满意', value: 'very_dissatisfied' },
      ],
    },
    {
      id: 'problems_encountered',
      type: 'multiple',
      title: '你在使用 WebUI 时遇到过哪些问题？',
      description: '可多选',
      required: true,
      options: [
        { id: 'lag', label: '界面卡顿', value: 'lag' },
        { id: 'incomplete', label: '功能不完整', value: 'incomplete' },
        { id: 'complex', label: '操作复杂', value: 'complex' },
        { id: 'bugs', label: '存在 Bug', value: 'bugs' },
        { id: 'none', label: '没有遇到问题', value: 'none' },
        { id: 'other', label: '其他', value: 'other' },
      ],
    },
    {
      id: 'problems_other',
      type: 'text',
      title: '如选择"其他"，请说明遇到的问题',
      required: false,
      placeholder: '请描述你遇到的其他问题...',
      maxLength: 500,
    },
    {
      id: 'useful_features',
      type: 'textarea',
      title: '你觉得哪些功能是最有用的？',
      required: true,
      placeholder: '请分享你认为最有价值的功能...',
      maxLength: 1000,
    },
    {
      id: 'feature_requests',
      type: 'textarea',
      title: '你希望在未来的版本中增加哪些功能？',
      required: true,
      placeholder: '请告诉我们你期望的新功能...',
      maxLength: 1000,
    },
    {
      id: 'overall_satisfaction',
      type: 'single',
      title: '你对麦麦 WebUI 的整体满意度如何？',
      required: true,
      options: [
        { id: 'very_satisfied', label: '非常满意', value: 'very_satisfied' },
        { id: 'satisfied', label: '满意', value: 'satisfied' },
        { id: 'neutral', label: '一般', value: 'neutral' },
        { id: 'dissatisfied', label: '不满意', value: 'dissatisfied' },
        { id: 'very_dissatisfied', label: '非常不满意', value: 'very_dissatisfied' },
      ],
    },
    {
      id: 'would_recommend',
      type: 'single',
      title: '你愿意推荐麦麦 WebUI 给其他人使用吗？',
      required: true,
      options: [
        { id: 'yes', label: '是', value: 'yes' },
        { id: 'no', label: '否', value: 'no' },
      ],
    },
    {
      id: 'other_suggestions',
      type: 'textarea',
      title: '其他建议或意见',
      description: '此项为选填',
      required: false,
      placeholder: '如果你有任何其他想法或建议，请在此分享...',
      maxLength: 2000,
    },
  ],
  settings: {
    allowMultiple: false,
    thankYouMessage: '感谢你的反馈！你的意见对我们非常重要，我们会认真考虑每一条建议。',
  },
}
